# Site settings
title: Jeffrey Herrera | Designer
email: herrera.jeffrey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of Jeffrey Herrera.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeffreyherrera.com" # the base hostname & protocol for your site
twitter_username: isthatjeff
github_username:  jeffreyh769

# Build settings
markdown: kramdown
permalink: pretty

# Navigation


